version: '3'
services:
  connectivitytest:
    build: .
    ports:
      - "5000:5000"  # Map port 5000 on the host to port 5000 in the container
    volumes:
      - ./app:/app        # Mount the current directory to /app inside the container
    environment:
      FLASK_ENV: development  # Set the environment to development
    command: python app.py    # Run the application
